# Generated by Django 6.0.3 on 2026-03-09 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0002_initial'),
        ('eval', '0016_alter_evalindicator_id_alter_evalproject_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='escalate_comment',
            field=models.TextField(blank=True, help_text='院系主任处理意见'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='escalated_to',
            field=models.ForeignKey(blank=True, help_text='上报对象（院系主任）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appeal',
            name='indicator',
            field=models.ForeignKey(blank=True, help_text='针对具体指标的申诉；为空表示整份提交申诉', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='eval.evalindicator'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='is_escalated',
            field=models.BooleanField(default=False, help_text='是否已上报院系主任'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('approved', '已通过'), ('rejected', '已驳回'), ('escalated', '已上报')], default='pending', max_length=20),
        ),
    ]
