# Generated by Django 4.2.20 on 2026-03-10 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appeal', '0003_appeal_escalate_comment_appeal_escalated_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='超级管理员处理意见'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='escalated_to_admin',
            field=models.ForeignKey(blank=True, help_text='二级上报对象（超级管理员）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_escalated_appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('approved', '已通过'), ('rejected', '已驳回'), ('escalated', '已上报院系主任'), ('escalated_to_admin', '已上报超级管理员')], default='pending', max_length=20),
        ),
    ]
