# Generated by Django 4.2.20 on 2026-03-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0004_add_admin_escalation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='original_submission_status',
            field=models.CharField(blank=True, default='', help_text='发起申诉前的提交状态，用于撤回时恢复', max_length=20),
        ),
    ]
