# Generated by Django 4.2.20 on 2026-03-23 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_add_title_user_nullable_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appeal', '0007_alter_appeal_id_alter_appealattachment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='title',
            field=models.CharField(blank=True, default='', help_text='独立申诉主题；指标级/整份提交申诉可留空', max_length=200),
        ),
        migrations.AddField(
            model_name='appeal',
            name='user',
            field=models.ForeignKey(blank=True, help_text='申诉发起人；独立申诉必填，旧申诉通过 submission.user 推断', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filed_appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='submission',
            field=models.ForeignKey(blank=True, help_text='关联提交；独立申诉可为空', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='submission.studentsubmission'),
        ),
        migrations.AlterField(
            model_name='appealattachment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
