# Generated by Django 6.0.3 on 2026-03-04 01:44

from django.db import migrations, models


# 初始层级：仅用于迁移中为已有角色赋值，后续可在后台修改
CODE_LEVEL_MAP = {
    'student': 0,
    'counselor': 1,
    'reviewer': 2,
    'director': 3,
    'admin': 4,
    'superadmin': 5,
}


def set_role_levels(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    for code, level in CODE_LEVEL_MAP.items():
        Role.objects.filter(code=code).update(level=level)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_current_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['level', 'id']},
        ),
        migrations.AddField(
            model_name='role',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, help_text='层级，0 最低，数字越大权限越高；分配某角色时自动拥有该 level 及以下所有角色'),
        ),
        migrations.RunPython(set_role_levels, noop),
    ]
