# Generated by Django 6.0.3 on 2026-03-06 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_role_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedUserBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_user_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_imported_user_batch',
                'ordering': ['-created_at'],
            },
        ),
    ]
