# Generated by Django 6.0.3 on 2026-03-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='importeduserbatch',
            name='current_count',
            field=models.PositiveIntegerField(default=0, help_text='已处理行数（含失败）'),
        ),
        migrations.AddField(
            model_name='importeduserbatch',
            name='hash_iterations',
            field=models.PositiveIntegerField(blank=True, help_text='本批次使用的密码哈希迭代次数，NULL 表示默认', null=True),
        ),
        migrations.AddField(
            model_name='importeduserbatch',
            name='warning_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='首次登录强制修改密码（批量导入用户自动置 True）'),
        ),
    ]
