# Generated by Django 4.2.20 on 2026-03-10 01:26

from django.db import migrations


def populate_name(apps, schema_editor):
    """
    将已有用户的 last_name + first_name 合并写入 name 字段，
    然后清空 first_name / last_name（中文习惯：姓在前名在后）。
    """
    User = apps.get_model('users', 'User')
    for user in User.objects.all().iterator():
        combined = f'{user.last_name}{user.first_name}'.strip()
        if not combined:
            combined = user.first_name or user.last_name or ''
        if combined:
            user.name = combined
            user.first_name = ''
            user.last_name = ''
            user.save(update_fields=['name', 'first_name', 'last_name'])


def reverse_populate(apps, schema_editor):
    """反向迁移：将 name 回写到 first_name。"""
    User = apps.get_model('users', 'User')
    for user in User.objects.all().iterator():
        if user.name and not user.first_name:
            user.first_name = user.name
            user.save(update_fields=['first_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_name_field'),
    ]

    operations = [
        migrations.RunPython(populate_name, reverse_populate),
    ]
