# Generated by Django 6.0.3 on 2026-03-03 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eval', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/%Y/%m/')),
                ('category', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'submission_evidence',
                'ordering': ['submission', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('under_review', '审核中'), ('approved', '已通过'), ('rejected', '已驳回'), ('appealing', '申诉中')], default='draft', max_length=20)),
                ('self_score', models.JSONField(blank=True, default=dict, help_text='自评分数明细')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, help_text='系统计算或管理员覆盖的最终总分', max_digits=6, null=True)),
                ('score_detail', models.JSONField(blank=True, default=dict, help_text='各指标/模块得分明细')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='eval.evalproject')),
            ],
            options={
                'db_table': 'submission_student_submission',
                'ordering': ['-created_at'],
            },
        ),
    ]
