# Generated by Django 6.0.3 on 2026-03-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='via_late_channel',
            field=models.BooleanField(default=False, help_text='True 表示该提交是在正常提交窗口和迟交窗口均已关闭后，通过管理员开启的补交通道提交的', verbose_name='通过补交通道提交'),
        ),
    ]
