# Generated by Django 6.0.3 on 2026-03-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_submissionanswer_and_evidence_indicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionanswer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
