# Generated by Django 4.2.20 on 2026-03-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_alter_submissionanswer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='submissionanswer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
