"""
Django settings for CompreEvalSystem project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 加载 .env 文件（项目根目录）；生产环境可通过系统环境变量覆盖，无需 .env 文件
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-&qy%((sluel542r=$ti=4fm$)8cm10%s@dn50gc%=2ss^7wkr)'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# 多个主机用英文逗号分隔，例如：54.123.45.67,your-domain.com,localhost
ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if h.strip()
]


# Application definition
AUTH_USER_MODEL = 'users.User'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'corsheaders',
    # Project apps (org before users: User FK to Department/Class)
    'org',
    'users',
    'eval',
    'submission',
    'scoring',
    'appeal',
    'audit',
    'report',
    'dashboard',
    'realtime',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 采集请求 IP / User-Agent，供操作日志自动填充
    'audit.middleware.RequestLogMiddleware',
    # 单点登录：校验 X-Session-Key，新登录自动踢出旧会话
    'users.middleware.SSOMiddleware',
]

ROOT_URLCONF = 'CompreEvalSystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CompreEvalSystem.wsgi.application'
ASGI_APPLICATION = 'CompreEvalSystem.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# 已使用 MySQL（PyMySQL），数据库名 campus_eval

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'campus_eval'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', '123456'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'CONN_MAX_AGE': 600,
        'OPTIONS': {
            'charset': 'utf8mb4',
            # 直接设置 MySQL 会话时区，无需安装 MySQL 时区表（Windows 默认未安装）
            'init_command': "SET time_zone = '+08:00'",
        },
    }
}


# Password hashers: 首项为默认 hasher，尾部的 LowIter 仅用于批量导入时识别/验证
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
    'users.hashers.LowIterPBKDF2PasswordHasher',
]

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 媒体文件（用户上传）
# 通过 MEDIA_ROOT 环境变量可重定向到任意路径（绝对路径）或对象存储挂载点
# 留空则默认使用项目根目录下的 media/ 文件夹
_media_root_env = os.environ.get('MEDIA_ROOT', '').strip()
MEDIA_ROOT = Path(_media_root_env) if _media_root_env else BASE_DIR / 'media'
MEDIA_URL = '/media/'

# REST Framework & JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # 登录时更新 User.last_login，便于后台「用户管理」中「登录状态」显示是否已登录过
    'UPDATE_LAST_LOGIN': True,
}

# CORS 跨域
# 开发环境默认全放行；生产环境在 .env 中设置：
#   CORS_ALLOW_ALL_ORIGINS=False
#   CORS_ALLOWED_ORIGINS=http://54.123.45.67,https://your-domain.com
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'True') == 'True'
if not CORS_ALLOW_ALL_ORIGINS:
    CORS_ALLOWED_ORIGINS = [
        o.strip()
        for o in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
        if o.strip()
    ]

# 允许前端携带自定义头 X-Session-Key（SSO 单点登录会话校验）
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-client-public-ip',
    'x-session-key',
]

# 缓存后端
# CACHE_BACKEND=file（默认）：文件缓存，无需额外依赖，适合单机部署
# CACHE_BACKEND=redis  ：Redis 缓存，需要 Redis 服务，适合高并发生产环境
_cache_backend = os.environ.get('CACHE_BACKEND', 'file').strip().lower()

if _cache_backend == 'redis':
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.environ.get('CACHE_REDIS_URL', 'redis://127.0.0.1:6379/1'),
            'TIMEOUT': 604800,
        }
    }
else:
    _cache_loc_env = os.environ.get('CACHE_LOCATION', '').strip()
    _cache_location = _cache_loc_env if _cache_loc_env else str(BASE_DIR / 'cache')
    import os as _os_cache
    _os_cache.makedirs(_cache_location, exist_ok=True)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
            'LOCATION': _cache_location,
            'TIMEOUT': 604800,  # 默认 7 天，与 refresh token 同寿命
            'OPTIONS': {
                'MAX_ENTRIES': 10000,
            },
        }
    }

# 日志目录
# 通过 LOG_DIR 环境变量可重定向到任意绝对路径，留空则使用项目根目录下的 logs/
_log_dir_env = os.environ.get('LOG_DIR', '').strip()
_LOG_DIR = Path(_log_dir_env) if _log_dir_env else BASE_DIR / 'logs'
import os as _os
_os.makedirs(_LOG_DIR, exist_ok=True)

# Python 日志配置：将 WARNING 及以上级别的日志写入文件，同时在控制台输出
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] [{levelname}] [{name}] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_warning': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': _LOG_DIR / 'django_warning.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 10,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'file_error': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': _LOG_DIR / 'django_error.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 10,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_warning'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file_error'],
            'level': 'ERROR',
            'propagate': False,
        },
        # 项目内部各 app 的日志
        'audit': {
            'handlers': ['console', 'file_warning'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}
