# Generated by Django 6.0.3

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='org.department')),
            ],
            options={
                'db_table': 'org_major',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='org.major'),
        ),
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.CharField(blank=True, help_text='年级，如 2022、2023', max_length=20),
        ),
    ]
