# Generated by Django 6.0.3 on 2026-03-04 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_major_and_class_major'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['department', 'grade', 'name'], 'verbose_name_plural': 'Classes'},
        ),
    ]
