# Generated by Django 6.0.3 on 2026-03-04 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_alter_class_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'department', 'grade')},
        ),
    ]
