# Generated by Django 6.0.3 on 2026-03-04 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_unique_class_name_dept_grade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='major',
            unique_together={('name', 'department')},
        ),
    ]
