# Generated by Django 6.0.3 on 2026-03-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_unique_major_name_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='grades',
            field=models.JSONField(blank=True, default=list, help_text='该专业已有的年级列表，如 ["2021", "2022", "2023"]'),
        ),
    ]
