# Generated by Django 6.0.3 on 2026-03-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_add_grades_to_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='academic_year',
            field=models.CharField(blank=True, help_text='历史字段，已改为自动计算', max_length=20),
        ),
    ]
