# Generated by Django 6.0.3 on 2026-03-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True, help_text='管理员改分、补交开启等必填')),
                ('is_abnormal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackdoorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='backdoor_evidence/%Y/%m/')),
                ('open_at', models.DateTimeField(auto_now_add=True)),
                ('close_at', models.DateTimeField(blank=True, null=True)),
                ('auto_close_planned', models.DateTimeField(blank=True, help_text='如 24h 后自动关闭', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_backdoor_log',
                'ordering': ['-open_at'],
            },
        ),
    ]
