# Generated by Django 4.2.20 on 2026-03-04 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0003_remove_backdoorlog_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audit_attachments/%Y/%m/', verbose_name='附件文件')),
                ('file_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小（字节）')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='MIME类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '审计附件',
                'verbose_name_plural': '审计附件',
                'db_table': 'audit_attachment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(blank=True, help_text='操作时记录的用户名，防止账号删除后信息丢失', max_length=150, verbose_name='用户名快照')),
                ('role_snapshot', models.CharField(blank=True, help_text='操作时的角色名称，如"超级管理员"', max_length=50, verbose_name='角色快照')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='来源IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='浏览器标识')),
                ('module', models.CharField(choices=[('auth', '认证'), ('users', '用户管理'), ('org', '组织架构'), ('eval', '测评管理'), ('submission', '材料提交'), ('scoring', '评分'), ('appeal', '申诉'), ('report', '报表'), ('system', '系统')], max_length=20, verbose_name='业务模块')),
                ('action', models.CharField(help_text='如 login / create_season / delete_project 等', max_length=100, verbose_name='操作码')),
                ('level', models.CharField(choices=[('INFO', '一般'), ('NOTICE', '关键'), ('WARNING', '敏感'), ('CRITICAL', '高危')], default='INFO', max_length=10, verbose_name='日志等级')),
                ('target_type', models.CharField(blank=True, help_text='如 eval_season / eval_project / user', max_length=100, verbose_name='目标类型')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='目标ID')),
                ('target_repr', models.CharField(blank=True, help_text='人类可读的目标名称，如"2024-2025学年春季"', max_length=500, verbose_name='目标描述')),
                ('extra', models.JSONField(blank=True, default=dict, help_text='旧值/新值/其他上下文，JSON 格式', verbose_name='附加信息')),
                ('reason', models.TextField(blank=True, help_text='WARNING/CRITICAL 级操作必填', verbose_name='操作理由')),
                ('is_abnormal', models.BooleanField(default=False, verbose_name='异常标记')),
                ('is_audit_event', models.BooleanField(default=False, help_text='True 时在"审计日志"视图中展示，通常对应需要正式存档的高危操作', verbose_name='审计事件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'audit_operation_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='backdoorlog',
            options={'ordering': ['-open_at'], 'verbose_name': '补交通道记录', 'verbose_name_plural': '补交通道记录'},
        ),
        migrations.RemoveField(
            model_name='backdoorlog',
            name='evidence_file',
        ),
        migrations.AlterField(
            model_name='backdoorlog',
            name='auto_close_planned',
            field=models.DateTimeField(blank=True, help_text='如 24h 后自动关闭', null=True, verbose_name='计划自动关闭时间'),
        ),
        migrations.AlterField(
            model_name='backdoorlog',
            name='close_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='关闭时间'),
        ),
        migrations.AlterField(
            model_name='backdoorlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='backdoorlog',
            name='open_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='开启时间'),
        ),
        migrations.AlterField(
            model_name='backdoorlog',
            name='opened_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backdoor_logs', to=settings.AUTH_USER_MODEL, verbose_name='开启者'),
        ),
        migrations.AlterField(
            model_name='backdoorlog',
            name='reason',
            field=models.TextField(verbose_name='开启理由'),
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.AddField(
            model_name='auditattachment',
            name='operation_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='audit.operationlog', verbose_name='关联日志'),
        ),
        migrations.AddField(
            model_name='auditattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['user', 'created_at'], name='oplog_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['module', 'action'], name='oplog_module_action_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['level', 'created_at'], name='oplog_level_time_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['is_audit_event', 'created_at'], name='oplog_audit_time_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['is_abnormal', 'created_at'], name='oplog_abnormal_time_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['created_at'], name='oplog_time_idx'),
        ),
    ]
