# Generated by Django 6.0.3 on 2026-03-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_auditattachment_id_alter_backdoorlog_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='external_ip',
            field=models.GenericIPAddressField(blank=True, help_text='客户端上报的公网 IP（仅供审查参考，不用于安全判断）', null=True, verbose_name='外网IP'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='局域网真实 IP（来自 X-Forwarded-For 或 REMOTE_ADDR）', null=True, verbose_name='内网IP'),
        ),
    ]
