# Generated by Django 6.0.3 on 2026-03-04 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_add_external_ip'),
        ('eval', '0002_evalproject_import_config'),
        ('org', '0006_add_grades_to_major'),
        ('submission', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LateSubmitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='申请理由')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审批状态')),
                ('handle_comment', models.TextField(blank=True, verbose_name='处理意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_late_requests', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_requests', to='submission.studentsubmission', verbose_name='关联提交')),
            ],
            options={
                'verbose_name': '补交申请',
                'verbose_name_plural': '补交申请',
                'db_table': 'audit_late_submit_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LateSubmitChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('user', '指定用户'), ('class', '指定班级')], default='user', max_length=10, verbose_name='范围类型')),
                ('reason', models.TextField(verbose_name='开启理由')),
                ('duration_hours', models.PositiveIntegerField(default=24, help_text='最少 1 小时', verbose_name='有效时长（小时）')),
                ('open_at', models.DateTimeField(auto_now_add=True, verbose_name='开启时间')),
                ('planned_close_at', models.DateTimeField(verbose_name='计划关闭时间')),
                ('actual_close_at', models.DateTimeField(blank=True, null=True, verbose_name='实际关闭时间')),
                ('close_reason', models.CharField(blank=True, choices=[('auto_expire', '自动到期'), ('submitted', '学生已提交'), ('manual', '管理员手动关闭')], max_length=20, verbose_name='关闭原因')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_late_channels', to=settings.AUTH_USER_MODEL, verbose_name='关闭者')),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_late_channels', to=settings.AUTH_USER_MODEL, verbose_name='开启者')),
                ('project', models.ForeignKey(blank=True, help_text='为空表示对该用户/班级的所有项目均开放', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='late_channels', to='eval.evalproject', verbose_name='限定项目')),
                ('target_class', models.ForeignKey(blank=True, help_text='scope_type=class 时必填', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='late_channels', to='org.class', verbose_name='目标班级')),
                ('target_user', models.ForeignKey(blank=True, help_text='scope_type=user 时必填', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='late_channels', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
                ('from_request', models.OneToOneField(blank=True, help_text='由审批申请自动开启时关联，手动开启时为空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel', to='audit.latesubmitrequest', verbose_name='来源申请')),
            ],
            options={
                'verbose_name': '补交通道',
                'verbose_name_plural': '补交通道',
                'db_table': 'audit_late_submit_channel',
                'ordering': ['-open_at'],
            },
        ),
    ]
