# Generated by Django 6.0.3 on 2026-03-06 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_delete_backdoor_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateSubmitRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='late_request_attachments/%Y/%m/', verbose_name='附件文件')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='audit.latesubmitrequest', verbose_name='关联补交申请')),
            ],
            options={
                'verbose_name': '补交申请附件',
                'verbose_name_plural': '补交申请附件',
                'db_table': 'audit_late_submit_request_attachment',
                'ordering': ['request', 'uploaded_at'],
            },
        ),
    ]
