# Generated by Django 6.0.3 on 2026-03-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comment', models.TextField(blank=True)),
                ('triggered_reason', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scoring_arbitration_record',
                'ordering': ['submission', 'indicator'],
            },
        ),
        migrations.CreateModel(
            name='ImportedScoreBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scoring_imported_score_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedScoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('source', models.CharField(blank=True, help_text='如 physical_education', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scoring_imported_score_detail',
                'ordering': ['batch', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comment', models.TextField(blank=True)),
                ('round_type', models.PositiveSmallIntegerField(choices=[(1, '初评'), (2, '二评'), (3, '仲裁')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scoring_score_record',
                'ordering': ['submission', 'indicator', 'round_type'],
            },
        ),
    ]
