# Generated by Django 6.0.3 on 2026-03-03 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eval', '0001_initial'),
        ('scoring', '0001_initial'),
        ('submission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitrationrecord',
            name='arbitrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arbitration_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arbitrationrecord',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitration_records', to='eval.evalindicator'),
        ),
        migrations.AddField(
            model_name='arbitrationrecord',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitration_records', to='submission.studentsubmission'),
        ),
        migrations.AddField(
            model_name='importedscorebatch',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_batches', to='eval.evalproject'),
        ),
        migrations.AddField(
            model_name='importedscorebatch',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importedscoredetail',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='scoring.importedscorebatch'),
        ),
        migrations.AddField(
            model_name='importedscoredetail',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_score_details', to='eval.evalindicator'),
        ),
        migrations.AddField(
            model_name='importedscoredetail',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_score_details', to='submission.studentsubmission'),
        ),
        migrations.AddField(
            model_name='importedscoredetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_score_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_records', to='eval.evalindicator'),
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_records_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_records', to='submission.studentsubmission'),
        ),
        migrations.AlterUniqueTogether(
            name='scorerecord',
            unique_together={('submission', 'indicator', 'reviewer', 'round_type')},
        ),
    ]
