# Generated by Django 6.0.3 on 2026-03-07 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eval', '0008_reviewrule_allowed_assistant_count_per_submission_and_more'),
        ('scoring', '0002_initial'),
        ('submission', '0004_submissionanswer_and_evidence_indicator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('counselor', '评审老师（辅导员）'), ('assistant', '学生助理')], max_length=20)),
                ('round_type', models.PositiveSmallIntegerField(default=1)),
                ('strategy_mode', models.CharField(default='same_class', max_length=50)),
                ('assignment_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('assigned', '已分配'), ('completed', '已完成'), ('cancelled', '已取消')], default='assigned', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='eval.evalproject')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='submission.studentsubmission')),
            ],
            options={
                'db_table': 'scoring_review_assignment',
                'ordering': ['-created_at', 'id'],
                'unique_together': {('submission', 'reviewer', 'round_type', 'assignment_version')},
            },
        ),
    ]
