# Generated by Django 4.2.20 on 2026-03-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_alter_reviewassignment_role_type_and_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorerecord',
            name='is_delegated',
            field=models.BooleanField(default=False, help_text='是否为降权代劳（评分者最高角色 level 高于当前角色 level）'),
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='score_channel',
            field=models.CharField(choices=[('assignment', '按分配任务评分'), ('arbitration', '仲裁'), ('import', '批量导入')], default='assignment', help_text='评分通道：assignment=按分配任务 | arbitration=仲裁 | import=批量导入', max_length=30),
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='scorer_max_role_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='评分者所有角色中的最高 level', null=True),
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='scorer_role_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='评分时评分者的 current_role.level', null=True),
        ),
        migrations.AlterField(
            model_name='arbitrationrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='importedscorebatch',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='importedscoredetail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reviewassignment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scorerecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
