# Generated by Django 6.0.3 on 2026-03-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0006_add_score_context_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitrationrecord',
            name='arbitrator_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='仲裁者的最高角色等级，用于层级保护（高权限仲裁不可被低权限覆盖）', null=True),
        ),
        migrations.AlterField(
            model_name='arbitrationrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='importedscorebatch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='importedscoredetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reviewassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scorerecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
