# Generated by Django 4.2.20 on 2026-03-11 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submission', '0005_alter_submissionanswer_id'),
        ('eval', '0017_add_require_process_record'),
        ('scoring', '0007_add_arbitrator_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewObjection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_role', models.CharField(choices=[('assistant', '学生助理'), ('counselor', '评审老师')], default='assistant', max_length=20)),
                ('status', models.CharField(choices=[('pending_counselor', '待辅导员处理'), ('resolved_by_counselor', '辅导员已处理'), ('escalated_to_director', '已上报院系主任'), ('resolved_by_director', '院系主任已处理'), ('escalated_to_admin', '已上报超管'), ('resolved_by_admin', '超管已处理'), ('rejected', '已驳回')], default='pending_counselor', max_length=40)),
                ('current_handler_level', models.PositiveSmallIntegerField(default=2)),
                ('reason', models.TextField()),
                ('resolution_comment', models.TextField(blank=True)),
                ('resolved_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_objections_assigned', to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_objections', to='eval.evalindicator')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_objections_raised', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_objections', to='submission.studentsubmission')),
            ],
            options={
                'db_table': 'scoring_review_objection',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewObjectionAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='review_objection/%Y/%m/')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('objection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='scoring.reviewobjection')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_objection_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scoring_review_objection_attachment',
                'ordering': ['id'],
            },
        ),
    ]
